### ISSUE TITLE
Incorrect credentials, when using the correct ones.

### ISSUE THREAD

**Issue by mati09898** [RuiRC/Online-Soccer-Manager-Ad-Watch-Bot#8]
←[33mPressing Accept Button and Waiting 5 Seconds...←[0m
←[33mLogin Button clicked. Waiting 5 seconds for next actions...←[0m
←[32mUsername pasted: mati09898←[0m
←[32mPassword pasted: ********************←[0m
←[33mPressing Enter key←[0m
←[31mLogin failed: Incorrect Username or Password. Retrying...←[0m
Exception in thread Thread-4 (getTokens):
Traceback (most recent call last):
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Matia\Downloads\Online-Soccer-Manager-Ad-Watch-Bot-main\Cuenta Mati\OnlineSoccerManagerBot\controller.py", line 10, in getTokens
    self.manager.get_business_tokens(restart_event)  # Pass the event to the service
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matia\Downloads\Online-Soccer-Manager-Ad-Watch-Bot-main\Cuenta Mati\OnlineSoccerManagerBot\service.py", line 295, in get_business_tokens
    self.login(self.user, self.password)
  File "C:\Users\Matia\Downloads\Online-Soccer-Manager-Ad-Watch-Bot-main\Cuenta Mati\OnlineSoccerManagerBot\service.py", line 216, in login
    self.retry_login_process(user, password)
  File "C:\Users\Matia\Downloads\Online-Soccer-Manager-Ad-Watch-Bot-main\Cuenta Mati\OnlineSoccerManagerBot\service.py", line 272, in retry_login_process
    self.driver.find_element("css selector", '#manager-name').send_keys(user)
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 231, in send_keys
    self._execute(
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <div id="manager-name" class="header-title vertical-center"> is not reachable by keyboard
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:353:5
webdriverSendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:668:13
interaction.sendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:642:11
sendKeysToElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:540:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:150:31

**Comment by mati09898** [comment]
Sometimes it logs in but after the 10 ads, when it restarts this error happens again.

**Comment by RuiRC** [comment]
Typically it should retry the login process until it is able to login, please try the most recent version and let me know

**Comment by mati09898** [comment]
yes I have the latest version, it try's to log in a couple of times and then it sends the error.

**Comment by mati09898** [comment]
![Screenshot 2024-05-02 at 15 56 25](https://github.com/RuiRC/Online-Soccer-Manager-Ad-Watch-Bot/assets/39603813/0837487b-8a9a-4cc2-84a9-02d27148565f)

**Comment by mati09898** [comment]
![Screenshot 2024-05-02 at 15 59 33](https://github.com/RuiRC/Online-Soccer-Manager-Ad-Watch-Bot/assets/39603813/9ace5fbf-a552-4be7-9992-7009154396fe)

**Comment by mati09898** [comment]
this is the error that also crashes the program, apparently it shows a dialog box with the manager name

**Comment by mati09898** [comment]
←[33mRestarting in 8 minutes...←[0m
←[33mRestarting in 7 minutes...←[0m
←[33mRestarting in 6 minutes...←[0m
←[33mRestarting in 5 minutes...←[0m
←[33mRestarting in 4 minutes...←[0m
←[33mRestarting in 3 minutes...←[0m
←[33mRestarting in 2 minutes...←[0m
←[33mRestarting in 1 minutes...←[0m
←[32mRestarting now...←[0m
←[31mError occurred while watching ad: 'NoneType' object has no attribute 'find_element'
Refreshing page and retrying...←[0m
Exception in thread Thread-7 (getTokens):
Traceback (most recent call last):
  File "C:\Users\Matia\Downloads\Online-Soccer-Manager-Ad-Watch-Bot-main\Cuenta Mati\OnlineSoccerManagerBot\service.py", line 309, in get_business_tokens
    storepage = self.driver.find_element('css selector', 'li.dropdown:nth-child(3)')
                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_element'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Matia\Downloads\Online-Soccer-Manager-Ad-Watch-Bot-main\Cuenta Mati\OnlineSoccerManagerBot\controller.py", line 10, in getTokens
    self.manager.get_business_tokens(restart_event)  # Pass the event to the service
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matia\Downloads\Online-Soccer-Manager-Ad-Watch-Bot-main\Cuenta Mati\OnlineSoccerManagerBot\service.py", line 393, in get_business_tokens
    self.driver.refresh()  # Refresh the page to attempt to recover from the error
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'refresh'
Restarting after wait...
←[33mPressing Accept Button and Waiting 5 Seconds...←[0m
←[33mLogin Button clicked. Waiting 5 seconds for next actions...←[0m
←[32mUsername pasted: mati09898←[0m
←[32mPassword pasted: ********************←[0m
←[33mPressing Enter key←[0m
←[31mLogin failed: Incorrect Username or Password. Retrying...←[0m
Exception in thread Thread-10 (getTokens):
Traceback (most recent call last):
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Matia\Downloads\Online-Soccer-Manager-Ad-Watch-Bot-main\Cuenta Mati\OnlineSoccerManagerBot\controller.py", line 10, in getTokens
    self.manager.get_business_tokens(restart_event)  # Pass the event to the service
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matia\Downloads\Online-Soccer-Manager-Ad-Watch-Bot-main\Cuenta Mati\OnlineSoccerManagerBot\service.py", line 295, in get_business_tokens
    self.login(self.user, self.password)
  File "C:\Users\Matia\Downloads\Online-Soccer-Manager-Ad-Watch-Bot-main\Cuenta Mati\OnlineSoccerManagerBot\service.py", line 216, in login
    self.retry_login_process(user, password)
  File "C:\Users\Matia\Downloads\Online-Soccer-Manager-Ad-Watch-Bot-main\Cuenta Mati\OnlineSoccerManagerBot\service.py", line 272, in retry_login_process
    self.driver.find_element("css selector", '#manager-name').send_keys(user)
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 231, in send_keys
    self._execute(
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Matia\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <div id="manager-name" class="header-title vertical-center"> is not reachable by keyboard
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:353:5
webdriverSendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:668:13
interaction.sendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:642:11
sendKeysToElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:540:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:150:31

No restart needed. Exiting...

**Comment by mati09898** [comment]
this happens after two restarts, it works ok and randomly it doesn't

**Comment by RuiRC** [comment]
I wish I could help you however this issue seems to be exclusive to you, from the logs I can tell you're using an older version so please pull or download the most recent one. Let me know if it helps

**Comment by mati09898** [comment]
I downloaded the 0.2, with the modifications from 2 weeks ago, is there a new one?

**Comment by RuiRC** [comment]
> I downloaded the 0.2, with the modifications from 2 weeks ago, is there a new one?

Yes, there is a new one with a small correction on the code which should make it loop even when the thread crashes. In theory it should fix your issues, about the login retries I've seen 10 attempts before being successful and times when it was just impossible to login. Not sure if it was a bug or not but the OSM website is a mess

**Comment by mati09898** [comment]
ok, ill leave it running and tell you after.

**Comment by mati09898** [comment]
No restart needed. Exiting...
Pressing Accept Button and Waiting 5 Seconds...
Login Button clicked. Waiting 5 seconds for next actions...
Username pasted: mati09898
Password pasted: ********************
Pressing Enter key
Login failed: Incorrect Username or Password. Retrying...
Exception in thread Thread-58 (getTokens):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/controller.py", line 10, in getTokens
    self.manager.get_business_tokens(restart_event)  # Pass the event to the service
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/service.py", line 295, in get_business_tokens
    self.login(self.user, self.password)
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/service.py", line 216, in login
    self.retry_login_process(user, password)
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/service.py", line 272, in retry_login_process
    self.driver.find_element("css selector", '#manager-name').send_keys(user)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 231, in send_keys
    self._execute(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <div id="manager-name" class="header-title vertical-center"> is not reachable by keyboard
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:353:5
webdriverSendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:668:13
interaction.sendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:642:11
sendKeysToElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:540:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:150:31

No restart needed. Exiting...
Pressing Accept Button and Waiting 5 Seconds...
Login Button clicked. Waiting 5 seconds for next actions...
Username pasted: mati09898
Password pasted: ********************
Pressing Enter key
Login failed: Incorrect Username or Password. Retrying...
Username pasted: mati09898
Password pasted: ********************
Pressing Enter key
Login failed: Incorrect Username or Password. Retrying...
Pressing Accept Button and Waiting 5 Seconds...
Exception in thread Thread-59 (getTokens):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/controller.py", line 10, in getTokens
    self.manager.get_business_tokens(restart_event)  # Pass the event to the service
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/service.py", line 295, in get_business_tokens
    self.login(self.user, self.password)
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/service.py", line 220, in login
    self.normal_login_process(user, password)
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/service.py", line 248, in normal_login_process
    login_button = WebDriverWait(self.driver, 10).until(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

No restart needed. Exiting...
Pressing Accept Button and Waiting 5 Seconds...
Login Button clicked. Waiting 5 seconds for next actions...
Username pasted: mati09898
Password pasted: ********************
Pressing Enter key
Login failed: Incorrect Username or Password. Retrying...
Exception in thread Thread-60 (getTokens):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/controller.py", line 10, in getTokens
    self.manager.get_business_tokens(restart_event)  # Pass the event to the service
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/service.py", line 295, in get_business_tokens
    self.login(self.user, self.password)
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/service.py", line 216, in login
    self.retry_login_process(user, password)
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/service.py", line 272, in retry_login_process
    self.driver.find_element("css selector", '#manager-name').send_keys(user)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 231, in send_keys
    self._execute(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <div id="manager-name" class="header-title vertical-center"> is not reachable by keyboard
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:353:5
webdriverSendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:668:13
interaction.sendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:642:11
sendKeysToElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:540:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:150:31

No restart needed. Exiting...
Pressing Accept Button and Waiting 5 Seconds...
Login Button clicked. Waiting 5 seconds for next actions...
Username pasted: mati09898
Password pasted: ********************
Pressing Enter key
Login failed: Incorrect Username or Password. Retrying...
Exception in thread Thread-61 (getTokens):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/controller.py", line 10, in getTokens
    self.manager.get_business_tokens(restart_event)  # Pass the event to the service
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/service.py", line 295, in get_business_tokens
    self.login(self.user, self.password)
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/service.py", line 216, in login
    self.retry_login_process(user, password)
  File "/Users/matiasperez/Downloads/Online-Soccer-Manager-Ad-Watch-Bot-main-2/OnlineSoccerManagerBot/service.py", line 272, in retry_login_process
    self.driver.find_element("css selector", '#manager-name').send_keys(user)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 231, in send_keys
    self._execute(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <div id="manager-name" class="header-title vertical-center"> is not reachable by keyboard
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:353:5
webdriverSendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:668:13
interaction.sendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:642:11
sendKeysToElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:540:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:150:31

No restart needed. Exiting...

**Comment by mati09898** [comment]
it got stuck like this.
